 [prune]
   non-go = true
   go-tests = true
   unused-packages = true

[[constraint]]
  name = "github.com/Masterminds/semver"
  version = "1.4.0"

[[constraint]]
  branch = "master"
  name = "github.com/yookoala/realpath"
